spring:
  datasource:
    url: jdbc:mysql://mysql:3306/voice-cut-1_dev_database
    # 해커톤 필요 시 username, password을 Github Secrets 관리
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
