spring:
  application:
    name: test
  datasource:
    url: jdbc:mysql://localhost:3306/local_database
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
