name: CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Debug build outputs
        run: pkill -f 'java -jar' || echo "No application running"
      - name: Deploy application as a service
        run: |
          echo "[Unit]
          Description=Spring Boot Application
          After=network.target

          [Service]
          ExecStart=/usr/bin/java -jar /path/to/build/libs/test-0.0.1-SNAPSHOT.jar
          WorkingDirectory=/path/to/build/libs
          Restart=always
          User=admin

          [Install]
          WantedBy=multi-user.target" | sudo tee /etc/systemd/system/spring-boot-app.service

          sudo systemctl daemon-reload
          sudo systemctl enable spring-boot-app
          sudo systemctl restart spring-boot-app

